### PR TITLE
CI: more container OS variants

### PR DESCRIPTION
**Pull request by benibr**

### CODE REVIEW

**Comment by jonasbardino** [comment]
Is it possible to rebase the PR or similar to get the CI to re-run with the latest `tests`, which succeeded in the CI triggered by my latest push? I tried a simple re-run from the failed CI run linked in details here, but it fails again because it stays on the previous commit without the curl upgrade in tests.

**Comment by jonasbardino** [comment]
So far so good. I can reproduce a 502 in the https test for rocky8 locally here, however, so that is probably another issue :-/

**Comment by jonasbardino** [comment]
After adding build support for the python2 version of mod_wsgi in `Dockerfile.rocky8` it works with and without `PREFER_PYTHON3` set. We explicitly set it to True in our rocky8 test instance, so we didn't hit the issue there.

**Comment by jonasbardino** [comment]
If you force push another PR update I guess it will merge cleanly now as CI from my last push passed without errors.

**Comment by benibr** [comment]
> After adding build support for the python2 version of mod_wsgi in `Dockerfile.rocky8` it works with and without `PREFER_PYTHON3` set. We explicitly set it to True in our rocky8 test instance, so we didn't hit the issue there.

Thanks for investigating, I just wanted to start diff'ing our prod .envs because I know I stumbled upon this multiple time during testing but couldn't remember the exact parameter that was causing it.
Since this is a error that is not easy to find, do you think we should add this to the troubleshooting section in the docs?

**Comment by jonasbardino** [comment]
Well, this particular cause should be eliminated now, and we are moving to a situation where python2 will finally disappear this summer. Yet, documenting where to look if the `migrid` container fails to start like this would be good. 
We saw a similar case of `httpd` refusing to launch when the usual upgrade of the OpenID Connect auth module failed because of upstream pulling the older RHEL/CentOS 7 rpm package upon new releases and docker builds therefore ended up with the outdated distro version, which didn't support the required Apache conf options.

**Pull request merged**
